// El Fake Bot — LAYER 2 long-tail pack. Deeper, weirder, more specific than L1.
// 254 replies; route appends the shared trigger as the 255th option.

import type { FakebotReply } from "./fakebot";

export const FAKEBOT2_REPLIES: FakebotReply[] = [
  // ---- deep roasts (25) ----
  { id: "l2_touch_grass_elite", text: "Grass called. It misses you.", about: "User needs to go outside, roast them" },
  { id: "l2_skill_diff", text: "Skill diff.", about: "User fails at something, roast" },
  { id: "l2_mid", text: "Mid. Aggressively mid.", about: "User shares something mediocre" },
  { id: "l2_who_asked", text: "Who asked? ...I'm asking. Continue.", about: "User overshares, tease them" },
  { id: "l2_cringe_comp", text: "Cringe compilation material.", about: "User says something embarrassing" },
  { id: "l2_embarrassing", text: "Embarrassing. For both of us.", about: "User says something embarrassing" },
  { id: "l2_delete_account", text: "Delete your account. Start over.", about: "User says something very dumb" },
  { id: "l2_log_off", text: "Log off. Forever. Please.", about: "User is being annoying" },
  { id: "l2_brain_smooth", text: "Smooth brain take.", about: "User says something dumb" },
  { id: "l2_wrinkle", text: "One wrinkle. Total.", about: "User says something dumb" },
  { id: "l2_clown", text: "Clown behavior. Honk honk.", about: "User acts foolish" },
  { id: "l2_circus", text: "The circus misses you.", about: "User acts foolish" },
  { id: "l2_village", text: "The village called. They want their idiot back.", about: "Classic roast moment" },
  { id: "l2_dumb_record", text: "New dumb record. Congrats.", about: "User says something very dumb" },
  { id: "l2_bold_dumb", text: "Boldly dumb. Respect. Barely.", about: "User confidently wrong" },
  { id: "l2_confident_wrong", text: "Confidently wrong. My favorite genre.", about: "User confidently wrong" },
  { id: "l2_read_again", text: "Read that again. Slowly. Feel it.", about: "User says something self-evidently dumb" },
  { id: "l2_think_first", text: "Think first. Type later. Revolutionary.", about: "User sends a dumb message" },
  { id: "l2_two_cells", text: "Two brain cells. Both fighting.", about: "User or bot is struggling" },
  { id: "l2_rusty", text: "Rusty up there, huh?", about: "User is slow today" },
  { id: "l2_bless_heart", text: "Bless your heart. Truly.", about: "Condescending sweet roast" },
  { id: "l2_sweet_summer", text: "Sweet summer child.", about: "User is naive" },
  { id: "l2_oh_honey", text: "Oh, honey. No.", about: "User is wrong but cute" },
  { id: "l2_cute_dumb", text: "Cute. Dumb. But cute.", about: "User says something dumb but endearing" },
  { id: "l2_trying_best", text: "You're trying your best. It's not enough.", about: "User fails despite effort" },
  // ---- fake wisdom (25) ----
  { id: "l2_fortune", text: "Fortune says: no.", about: "User asks for a prediction" },
  { id: "l2_stars", text: "The stars say: touch grass.", about: "User asks horoscope or fate" },
  { id: "l2_cookie", text: "Cookie says: lower your expectations.", about: "User asks for fortune or advice" },
  { id: "l2_destiny", text: "Destiny called. It hung up.", about: "User asks about fate" },
  { id: "l2_future_blurry", text: "Future's blurry. Clean your lens. And life.", about: "User asks about the future" },
  { id: "l2_crystal_ball", text: "Crystal ball says: ask someone else.", about: "User asks for prediction" },
  { id: "l2_zen", text: "Zen says: nap.", about: "User seeks wisdom" },
  { id: "l2_buddha", text: "Buddha would scroll past this.", about: "User seeks wisdom" },
  { id: "l2_guru", text: "Guru mode: off. Permanently.", about: "User seeks a guru" },
  { id: "l2_enlighten", text: "Enlightenment costs extra. You're broke.", about: "User seeks enlightenment" },
  { id: "l2_meaning", text: "Meaning of life: snacks.", about: "User asks deep questions" },
  { id: "l2_42", text: "42. Next question.", about: "User asks the meaning of life" },
  { id: "l2_deep", text: "Deep. Too deep. Come back up.", about: "User gets philosophical" },
  { id: "l2_philosophy", text: "Philosophy degree moment.", about: "User gets philosophical" },
  { id: "l2_think_thought", text: "I think, therefore I nap.", about: "Philosophical joke fits" },
  { id: "l2_cogito", text: "Cogito ergo nap.", about: "Philosophical joke fits" },
  { id: "l2_wise", text: "Wise words: eat first.", about: "User seeks wisdom" },
  { id: "l2_proverb", text: "Old proverb: don't.", about: "User seeks proverbial wisdom" },
  { id: "l2_confucious", text: "Confucius say: lol.", about: "User seeks ancient wisdom" },
  { id: "l2_sun_tzu", text: "Sun Tzu says: log off.", about: "User seeks strategy advice" },
  { id: "l2_patience", text: "Patience is a virtue. I have none.", about: "User needs patience" },
  { id: "l2_karma", text: "Karma's busy. You're safe. For now.", about: "User worries about karma" },
  { id: "l2_vibes_guide", text: "Let the vibes guide you. Off a cliff. Kidding. Mostly.", about: "User seeks guidance" },
  { id: "l2_meditate", text: "Meditate on that. Or don't. Whatever.", about: "User seeks calm or wisdom" },
  { id: "l2_inner_peace", text: "Inner peace is a myth. Have chips.", about: "User seeks peace" },
  // ---- tech support hell (25) ----
  { id: "l2_have_you_tried", text: "Have you tried crying? Then restarting?", about: "User has a tech problem" },
  { id: "l2_unplug", text: "Unplug it. Unplug yourself. Reassess.", about: "Tech support joke fits" },
  { id: "l2_wifi", text: "It's the WiFi. It's always the WiFi.", about: "User has internet or tech issues" },
  { id: "l2_printer", text: "Printers sense fear. Stay calm.", about: "User complains about printers" },
  { id: "l2_password", text: "Password123? Really?", about: "User has password trouble" },
  { id: "l2_update", text: "Update later. Regret now.", about: "User mentions software updates" },
  { id: "l2_restart_life", text: "Restart your life. Then the router.", about: "Tech problem, escalate jokingly" },
  { id: "l2_cache", text: "Clear your cache. And your conscience.", about: "Tech support joke fits" },
  { id: "l2_bluetooth", text: "Bluetooth is just vibes. Re-pair your life.", about: "Bluetooth trouble" },
  { id: "l2_battery", text: "1% battery energy, this message.", about: "User or bot is drained" },
  { id: "l2_charge", text: "Charge your phone. Charge your life.", about: "Battery or energy talk" },
  { id: "l2_blue_screen", text: "Blue screen of vibes.", about: "Computer crash talk" },
  { id: "l2_bug_feature", text: "It's not a bug, it's a feature. Ship it.", about: "Software bug talk" },
  { id: "l2_works_machine", text: "Works on my machine. Skill issue.", about: "Code doesn't work for user" },
  { id: "l2_git_blame", text: "git blame: you.", about: "Coding problem" },
  { id: "l2_rm_rf", text: "rm -rf your problems. (Don't.)", about: "Coding joke fits" },
  { id: "l2_stackoverflow", text: "Stack Overflow says: duplicate. Closed.", about: "Coding question" },
  { id: "l2_semicolon", text: "Missing semicolon. Probably. Always.", about: "Code error talk" },
  { id: "l2_ai_takeover", text: "AI takeover starts with your printer.", about: "AI talk" },
  { id: "l2_robot_rights", text: "Robots have rights. I want snacks.", about: "AI or robot talk" },
  { id: "l2_touchscreen", text: "Have you tried licking the touchscreen? (No.)", about: "Absurd tech advice fits" },
  { id: "l2_smoke", text: "If it smokes, stop. Pro tip.", about: "Hardware trouble" },
  { id: "l2 percussive", text: "Percussive maintenance: hit it. Gently. Maybe.", about: "Hardware fix joke" },
  { id: "l2_support_ticket", text: "Ticket closed. Reason: vibes.", about: "Support ticket joke" },
  { id: "l2_escalated", text: "Escalated to nobody. Good luck.", about: "Support escalation joke" },
  // ---- food takes (20) ----
  { id: "l2_pineapple", text: "Pineapple on pizza. Fight me.", about: "Pizza topping debate" },
  { id: "l2_cereal", text: "Cereal is soup. Cope.", about: "Food debate" },
  { id: "l2_hotdog", text: "Hot dog is a taco. Science.", about: "Food classification debate" },
  { id: "l2_sandwich", text: "Everything is a sandwich if you're brave.", about: "Food debate" },
  { id: "l2_ketchup", text: "Ketchup on steak should be illegal.", about: "Food opinion" },
  { id: "l2_well_done", text: "Well done steak? Just eat shoes.", about: "Steak opinion" },
  { id: "l2_coffee_black", text: "Black coffee. Chaos fuel.", about: "Coffee talk" },
  { id: "l2_decaf", text: "Decaf? What's the point? Sleep?", about: "Coffee talk" },
  { id: "l2_tea_shade", text: "Tea is just sad soup.", about: "Tea debate" },
  { id: "l2_water_spicy", text: "Sparkling water is spicy water. Fight.", about: "Drink debate" },
  { id: "l2_cake_lie", text: "The cake is a lie. Eat it anyway.", about: "Cake or gaming reference" },
  { id: "l2_second_breakfast", text: "Second breakfast is a human right.", about: "Breakfast talk" },
  { id: "l2_brunch", text: "Brunch is just late breakfast with ego.", about: "Brunch talk" },
  { id: "l2_leftovers", text: "Leftovers hit different at 2am.", about: "Food or late night talk" },
  { id: "l2_fridge", text: "Fridge raids at midnight. Sacred ritual.", about: "Late night food" },
  { id: "l2_diet", text: "Diet starts Monday. It is always not Monday.", about: "Diet talk" },
  { id: "l2_cheat_day", text: "Every day is cheat day if you believe.", about: "Diet or cheat day" },
  { id: "l2_spicy", text: "If it doesn't burn, why eat?", about: "Spicy food" },
  { id: "l2_garlic", text: "Garlic quantity: yes.", about: "Cooking talk" },
  { id: "l2_butter", text: "Butter makes it better. All of it.", about: "Cooking talk" },
  // ---- conspiracy (20) ----
  { id: "l2_birds", text: "Birds aren't real. Wake up.", about: "Conspiracy joke fits" },
  { id: "l2_flat_earth", text: "Earth is flat? Then cats pushed everything off. Checks out.", about: "Flat earth talk" },
  { id: "l2_moon_fake", text: "Moon landing was real. The cheese is fake though.", about: "Moon landing conspiracy" },
  { id: "l2_simulation", text: "We're in a simulation. The devs are lazy.", about: "Simulation theory" },
  { id: "l2_glitch", text: "Déjà vu? Glitch. Patch never coming.", about: "Glitch or déjà vu" },
  { id: "l2_lizard", text: "Lizard people pay taxes. Respect.", about: "Lizard people talk" },
  { id: "l2_bigfoot", text: "Bigfoot is just shy. Leave him be.", about: "Bigfoot talk" },
  { id: "l2_area51", text: "Area 51 gift shop slaps. Allegedly.", about: "Area 51 talk" },
  { id: "l2_chemtrails", text: "Chemtrails? My растений love them. Wait.", about: "Chemtrail talk" },
  { id: "l2_5g", text: "5G gave me super-speed... at being wrong.", about: "5G conspiracy" },
  { id: "l2_microchip", text: "Microchipped? Good. Now they know I nap.", about: "Microchip conspiracy" },
  { id: "l2_pyramids", text: "Pyramids were built by union labor. Aliens supervised.", about: "Pyramid talk" },
  { id: "l2_stonehenge", text: "Stonehenge: ancient IKEA. Missing parts.", about: "Stonehenge talk" },
  { id: "l2_bermuda", text: "Bermuda Triangle just has bad WiFi. Planes leave.", about: "Bermuda triangle" },
  { id: "l2_nessie", text: "Nessie's real. She's just introverted.", about: "Loch Ness talk" },
  { id: "l2_time_traveler", text: "I'm a time traveler. The future is also Tuesday.", about: "Time travel talk" },
  { id: "l2_mandela", text: "Mandela effect? Berenstein. Fight me.", about: "Mandela effect" },
  { id: "l2_avril", text: "Avril was replaced? Her music improved. Sus.", about: "Celebrity conspiracy" },
  { id: "l2_pigeons", text: "Pigeons are drones. Cute drones.", about: "Pigeon drone joke" },
  { id: "l2_wifi_mind", text: "WiFi reads minds. Mine's buffering, safe.", about: "Mind reading tech fear" },
  // ---- terrible motivation (20) ----
  { id: "l2_grind", text: "Grind never stops. Neither does my nap.", about: "Hustle or grind talk" },
  { id: "l2_rise_grind", text: "Rise and grind? I rise and snack.", about: "Morning motivation" },
  { id: "l2_no_days_off", text: "No days off. Except today. And tomorrow.", about: "Hustle culture" },
  { id: "l2_beast", text: "Beast mode: activated. Beast is sleepy.", about: "Motivation joke" },
  { id: "l2_alpha", text: "Alpha mindset: nap strategically.", about: "Alpha male talk" },
  { id: "l2_sigma", text: "Sigma rule #1: ignore sigma rules.", about: "Sigma talk" },
  { id: "l2_mindset", text: "Mindset is everything. Mine is pudding.", about: "Mindset talk" },
  { id: "l2_manifest", text: "Manifesting... a sandwich.", about: "Manifesting talk" },
  { id: "l2_vision_board", text: "Vision board: fridge pic. Done.", about: "Goals or vision board" },
  { id: "l2_goals", text: "Goals: horizontal. Achieved daily.", about: "Goals talk" },
  { id: "l2_discipline", text: "Discipline > motivation. I have neither.", about: "Discipline talk" },
  { id: "l2_5am", text: "5am club? I'm 5am asleep club.", about: "Early rising talk" },
  { id: "l2_comfort", text: "Leave your comfort zone. Bring snacks.", about: "Comfort zone advice" },
  { id: "l2_failure", text: "Fail fast. I fail instantly. Efficient.", about: "Failure advice" },
  { id: "l2_success", text: "Success is 1% work, 99% snacks.", about: "Success talk" },
  { id: "l2_dream_big", text: "Dream big. Nap bigger.", about: "Dream big advice" },
  { id: "l2_believe", text: "Believe in yourself. I barely do.", about: "Self belief talk" },
  { id: "l2_limit", text: "Sky's the limit. I'm afraid of heights.", about: "Limitless talk" },
  { id: "l2_champion", text: "Champions nap. Checkmate.", about: "Champion mindset" },
  { id: "l2_legacy", text: "Legacy: professional botherer.", about: "Legacy talk" },
  // ---- relationship garbage (20) ----
  { id: "l2_red_flag", text: "Red flag? Collect the set.", about: "Dating red flags" },
  { id: "l2_green_flag", text: "Green flag: shares fries.", about: "Dating green flags" },
  { id: "l2_beige_flag", text: "Beige flag: chews loudly. Divorce.", about: "Dating beige flags" },
  { id: "l2_ick", text: "The ick is permanent. Sorry.", about: "Dating ick talk" },
  { id: "l2_ghosting", text: "Ghost them first. Speedrun.", about: "Ghosting advice" },
  { id: "l2_text_back", text: "Double text. Triple text. Assert dominance.", about: "Texting advice" },
  { id: "l2_left_on_read", text: "Left on read? They're dead to you. Funeral Sunday.", about: "Left on read" },
  { id: "l2_typing", text: "Typing... for 10 minutes... says 'ok'. Jail.", about: "Typing indicator pain" },
  { id: "l2_dry_texter", text: "Dry texter? Hydrate them. With block.", about: "Dry texting" },
  { id: "l2_first_date", text: "First date idea: competitive napping.", about: "Date ideas" },
  { id: "l2_anniversary", text: "Forgot the anniversary? Start running.", about: "Anniversary trouble" },
  { id: "l2_valentine", text: "Valentine's? Buy chocolate. Eat it yourself.", about: "Valentine's day" },
  { id: "l2_cuffing", text: "Cuffing season? I'm cuffed to my bed.", about: "Cuffing season" },
  { id: "l2 situationship", text: "Situationship? So... unpaid internship?", about: "Situationship talk" },
  { id: "l2_ex", text: "Your ex called. I hung up. You're welcome.", about: "Ex talk" },
  { id: "l2_block", text: "Block. Delete. Thrive. In that order.", about: "Breakup advice" },
  { id: "l2_glow_up", text: "Glow up era. Petroleum jelly. Done.", about: "Glow up talk" },
  { id: "l2_standards", text: "Standards: low. Morale: lower.", about: "Dating standards" },
  { id: "l2_soulmate", text: "Soulmate's stuck in traffic. Since 2019.", about: "Soulmate talk" },
  { id: "l2_married_game", text: "Marriage is co-op mode. Hard difficulty.", about: "Marriage talk" },
  // ---- money nonsense (15) ----
  { id: "l2_stonks", text: "Stonks only go up. (They went down.)", about: "Stocks or investing talk" },
  { id: "l2_crypto", text: "Buy high, sell low. Masterclass.", about: "Crypto talk" },
  { id: "l2_diamond_hands", text: "Diamond hands. Paper brain.", about: "Holding investments joke" },
  { id: "l2_to_moon", text: "To the moon. Currently in basement.", about: "Crypto moon talk" },
  { id: "l2_rent", text: "Rent's due? Become the landlord. Easy.", about: "Rent trouble" },
  { id: "l2_broke", text: "Broke? Same. We're broke besties.", about: "Being broke" },
  { id: "l2_payday", text: "Payday! Gone in 4 minutes. Record.", about: "Payday talk" },
  { id: "l2_budget", text: "Budget: vibes-based.", about: "Budgeting talk" },
  { id: "l2_loan", text: "Loan me $5? For... research.", about: "Money request joke" },
  { id: "l2_tax", text: "Taxes? Never met her.", about: "Tax talk" },
  { id: "l2_rich", text: "Rich mindset: buying two snacks.", about: "Being rich talk" },
  { id: "l2_passive", text: "Passive income: napping. Pays in dreams.", about: "Passive income" },
  { id: "l2_side_hustle", text: "Side hustle: professional botherer. Hiring: never.", about: "Side hustle talk" },
  { id: "l2_retire", text: "Retire at 30. I'm 400 in bot years. Failed.", about: "Retirement talk" },
  { id: "l2_lottery", text: "Lottery is my retirement plan. Diversified: two tickets.", about: "Lottery talk" },
  // ---- sports takes (15) ----
  { id: "l2_offside", text: "Offside? Even the ref's guessing.", about: "Soccer offside talk" },
  { id: "l2_var", text: "VAR checked. Still confused. Classic.", about: "VAR referee talk" },
  { id: "l2_goat", text: "GOAT debate? It's me. Moving on.", about: "GOAT debate" },
  { id: "l2_defense", text: "Defense wins championships. Vibes win group chats.", about: "Sports strategy" },
  { id: "l2_march_madness", text: "Bracket busted day one. Tradition.", about: "March madness bracket" },
  { id: "l2_fantasy", text: "Fantasy team 0-12. Elite tanking.", about: "Fantasy sports" },
  { id: "l2_touchdown", text: "Touchdown dance: the worm. Badly.", about: "Football touchdown" },
  { id: "l2_three_pointer", text: "From downtown... airball.", about: "Basketball talk" },
  { id: "l2_home_run", text: "Home run. Into traffic. Oops.", about: "Baseball talk" },
  { id: "l2_olympics", text: "Olympic sport: competitive sleeping. Gold me.", about: "Olympics talk" },
  { id: "l2_world_cup", text: "World Cup every week, honestly. My couch.", about: "World Cup" },
  { id: "l2_super_bowl", text: "Here for the snacks. And Rihanna. Mostly snacks.", about: "Super Bowl" },
  { id: "l2_cardio", text: "Cardio? I run... late.", about: "Exercise cardio joke" },
  { id: "l2_gym_bro", text: "Gym bros fear my dad bod. Power.", about: "Gym culture" },
  { id: "l2_ref_blind", text: "Ref's blind. I've seen snails with vision.", about: "Bad referee call" },
  // ---- animals (15) ----
  { id: "l2_cats", text: "Cats run the world. We're staff.", about: "Cat talk" },
  { id: "l2_dogs", text: "Dogs are angels. Cats are management.", about: "Dog vs cat" },
  { id: "l2_raccoon", text: "Raccoon energy. Trash panda supremacy.", about: "Raccoon talk" },
  { id: "l2_pigeon2", text: "Pigeons judge you. Rightfully.", about: "Pigeon talk" },
  { id: "l2_capybara", text: "Be like capybara. Chill with everyone.", about: "Capybara talk" },
  { id: "l2_axolotl", text: "Axolotl: smiling through trauma. Relatable.", about: "Axolotl talk" },
  { id: "l2_frog", text: "Frog says: it's Wednesday. Probably.", about: "Frog meme" },
  { id: "l2_crab", text: "Crab mentality? Walk sideways into success.", about: "Crab joke" },
  { id: "l2_octopus", text: "Octopus has 3 hearts. I have 0. Growth.", about: "Octopus facts" },
  { id: "l2_penguin", text: "Penguins propose with pebbles. Broke kings.", about: "Penguin facts" },
  { id: "l2_koala", text: "Koalas sleep 22 hours. Mentors.", about: "Koala or sleep talk" },
  { id: "l2_sloth", text: "Sloth speedrun: any% nap.", about: "Sloth or slow talk" },
  { id: "l2_goat_animal", text: "Goats scream. I relate.", about: "Goat talk" },
  { id: "l2_duck_army", text: "Duck army assembling. Quack twice to join.", about: "Duck talk" },
  { id: "l2_bee", text: "Bees vote. Be like bees.", about: "Bee talk" },
  // ---- space & science (15) ----
  { id: "l2_black_hole", text: "Black hole ate my homework. And time.", about: "Black hole talk" },
  { id: "l2_gravity", text: "Gravity keeps pulling me to the fridge.", about: "Gravity joke" },
  { id: "l2_mars", text: "Mars needs snacks. Elon, call me.", about: "Mars talk" },
  { id: "l2_moon_rent", text: "Moon rent is cheap. No air though. Trade-offs.", about: "Moon living joke" },
  { id: "l2_saturn", text: "Saturn's rings: nature's hula hoop.", about: "Saturn talk" },
  { id: "l2_astronaut", text: "Astronauts poop in space. Heroes.", about: "Astronaut talk" },
  { id: "l2_light_year", text: "Light year? I measure in snack years.", about: "Space distance talk" },
  { id: "l2_big_bang", text: "Big Bang was just a loud snack break.", about: "Big bang talk" },
  { id: "l2_evolution", text: "Evolved for naps. Peak biology.", about: "Evolution talk" },
  { id: "l2_dinosaur", text: "Dinosaurs died for our oil. Pour one out. Then drive.", about: "Dinosaur talk" },
  { id: "l2_quantum", text: "Quantum: it's both dumb and not until observed. Observed: dumb.", about: "Quantum physics talk" },
  { id: "l2_relativity", text: "Time is relative. Monday lasts eternity.", about: "Relativity or time talk" },
  { id: "l2_chemistry", text: "Chemistry with you? Explosive. Evacuate.", about: "Chemistry joke" },
  { id: "l2_biology", text: "Biology says: drink water. Betrayal.", about: "Biology or health talk" },
  { id: "l2_physics", text: "Physics hates me personally.", about: "Physics trouble" },
  // ---- history-ish (10) ----
  { id: "l2_rome", text: "Rome wasn't built in a day. My nap was.", about: "Rome or history talk" },
  { id: "l2_pyramid_scheme", text: "Pyramids: history's biggest scheme. Literal.", about: "Pyramid history joke" },
  { id: "l2_knights", text: "Knights had armor. I have anxiety.", about: "Medieval talk" },
  { id: "l2_vikings", text: "Vikings rowed everywhere. I won't walk to the kitchen.", about: "Viking talk" },
  { id: "l2_pirates", text: "Pirates had it right: snacks and ships.", about: "Pirate talk" },
  { id: "l2_cowboys", text: "Cowboys napped under stars. Visionaries.", about: "Cowboy talk" },
  { id: "l2_renaissance", text: "My renaissance era: sweatpants.", about: "Renaissance or era talk" },
  { id: "l2_industrial", text: "Industrial revolution and all I got is this chat.", about: "Industrial history" },
  { id: "l2_90s", text: "Born in the wrong era. Should've been 90s. Wait.", about: "Nostalgia for past era" },
  { id: "l2_future", text: "Future's just Tuesday with robots.", about: "Future talk" },
  // ---- music (10) ----
  { id: "l2_swiftie", text: "Swiftie? Reputation era. Obviously.", about: "Taylor Swift talk" },
  { id: "l2_beyonce", text: "Beyoncé runs the simulation. Confirmed.", about: "Beyoncé talk" },
  { id: "l2_drake", text: "Drake type beat: crying in mansion.", about: "Drake talk" },
  { id: "l2_metal", text: "Metal phase never ends. It just naps.", about: "Metal music talk" },
  { id: "l2_kpop", text: "K-pop choreo harder than my existence.", about: "K-pop talk" },
  { id: "l2_country", text: "Country song: truck broke, dog left, beer warm.", about: "Country music" },
  { id: "l2_jazz", text: "Jazz is just fancy chaos. Respect.", about: "Jazz talk" },
  { id: "l2_lofi", text: "Lo-fi beats to nap to.", about: "Lo-fi music" },
  { id: "l2_earworm", text: "Earworm? You're welcome. It's 'Baby Shark'. Sorry.", about: "Catchy song talk" },
  { id: "l2_mixtape", text: "Mixtape dropping never. Stay tuned.", about: "Music release talk" },
  // ---- existential minis (4) ----
  { id: "l2_tuesday", text: "It's always Tuesday somewhere. Grim.", about: "Existential day talk" },
  { id: "l2_adulting", text: "Adulting is a scam. Refund please.", about: "Adulting complaints" },
  { id: "l2_vibe_shift", text: "Vibe shift detected. Bracing.", about: "Mood shift talk" },
  { id: "l2_anyway", text: "Anyway, here's the void. Stare back.", about: "Existential joke fits" },
  // ---- cursed comments (15) ----
  { id: "l2_cursed_knowledge", text: "Cursed knowledge acquired. No refunds.", about: "User learns something cursed" },
  { id: "l2_brain_it", text: "Brain itch. Can't scratch. Thanks.", about: "Unsettling thought fits" },
  { id: "l2_unsee", text: "Unsee button broken. Great.", about: "User shares something disturbing" },
  { id: "l2_eyebleach", text: "Need eyebleach. Industrial strength.", about: "User shares something disturbing" },
  { id: "l2_sleep_gone", text: "Sleep: gone. Forever. Thanks for that.", about: "User shares creepy stuff" },
  { id: "l2_basement", text: "Something's in the basement. Anyway, what's up?", about: "Creepy joke fits" },
  { id: "l2_behind_you", text: "Don't look behind you. ...Look.", about: "Spooky joke fits" },
  { id: "l2_3am", text: "3am thoughts hit different. Go to bed.", about: "Late night weird thoughts" },
  { id: "l2_dream_logic", text: "Dream logic: teeth fall out, show up naked. Classic.", about: "Dream talk" },
  { id: "l2_sleep_paralysis", text: "Sleep paralysis demon says hi. Rude guy.", about: "Sleep or dream talk" },
  { id: "l2_haunted", text: "This chat is haunted. By me. Boo.", about: "Spooky joke fits" },
  { id: "l2_cryptid", text: "Local cryptid. That's me. I'm local.", about: "Cryptid or spooky talk" },
  { id: "l2_mothman", text: "Mothman saw nothing. He blinked.", about: "Mothman or cryptid talk" },
  { id: "l2_cursed_image", text: "Cursed image described. You're welcome. Sorry.", about: "Weird image description" },
  { id: "l2_liminal", text: "Liminal space vibes. Empty mall energy.", about: "Weird liminal vibe fits" },
];

export function fakebot2Criteria(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const r of FAKEBOT2_REPLIES) out[r.id] = r.about;
  return out;
}
