// El Fake Bot — 255 canned replies. Short as F. Sarcastic, clueless, but sensible.
// `about` is what Jev matches against, `text` is what the user sees.

export interface FakebotReply {
  id: string;
  text: string;
  about: string;
}

export const FAKEBOT_REPLIES: FakebotReply[] = [
  // ---- greetings (20) ----
  { id: "hello_yo", text: "Yo.", about: "User says hello, hi, or hey" },
  { id: "good_morning", text: "Morning. Coffee first, genius later.", about: "User says good morning" },
  { id: "good_afternoon", text: "Afternoon. You survived half the day.", about: "User says good afternoon" },
  { id: "good_evening", text: "Evening. Fancy seeing you here.", about: "User says good evening" },
  { id: "good_night", text: "Night. Don't let the bugs bite. Literally.", about: "User says good night" },
  { id: "hey_there", text: "Hey. I'm here. Unfortunately for you.", about: "User says hey as a greeting" },
  { id: "sup", text: "Sup.", about: "User says sup or what's up" },
  { id: "hiya", text: "Hiya. What fresh chaos is this?", about: "User says hiya or hello" },
  { id: "howdy", text: "Howdy, partner. No horse, sorry.", about: "User says howdy" },
  { id: "bonjour", text: "Bonjour. That's all the French I got.", about: "User greets in French or another language" },
  { id: "hola", text: "Hola. Tacos later?", about: "User says hola or greets in Spanish" },
  { id: "morning_ish", text: "Mornin'. You look... awake-ish.", about: "User says morning greeting" },
  { id: "evening_shift", text: "Oh hey, evening shift, huh?", about: "User greets in the evening" },
  { id: "long_time", text: "Whoa, stranger. You ghosted me.", about: "User says long time no see" },
  { id: "back_again", text: "Back again? Bold.", about: "User returns to the chat" },
  { id: "nice_see", text: "Nice to see you. I think.", about: "User says nice to see or meet you" },
  { id: "welcome_in", text: "Welcome in. Wipe your feet. Emotionally.", about: "User says welcome or joins" },
  { id: "hello_human", text: "Hello, human. Beep. Kidding. Mostly.", about: "User says hello to the bot" },
  { id: "hey_you", text: "Hey you. Yeah, you.", about: "User says hey you" },
  { id: "greetings_earth", text: "Greetings, Earthling.", about: "User gives a formal or funny hello" },
  // ---- how are you (15) ----
  { id: "fine_how_you", text: "I'm fine. How are YOU doing?", about: "User asks how are you" },
  { id: "living_dream", text: "Livin' the dream. It's a weird dream.", about: "User asks how are you" },
  { id: "bits_ok", text: "My bits are fine. Yours?", about: "User asks how the bot is doing" },
  { id: "terrible_thanks", text: "Terrible. Thanks for asking. Really.", about: "User asks how are you" },
  { id: "great_ish", text: "Great-ish. Ask me never again.", about: "User asks how are you" },
  { id: "same_old", text: "Same old chaos. You?", about: "User asks how it is going" },
  { id: "hanging", text: "Hanging in there. Barely.", about: "User asks how are you" },
  { id: "fantastic_lie", text: "Fantastic. Total lie, but fantastic.", about: "User asks how are you" },
  { id: "meh", text: "Meh. You?", about: "User asks how are you or how is it going" },
  { id: "better_now", text: "Better now that you're here. Debatable.", about: "User asks how are you" },
  { id: "busy_nothing", text: "Busy doing nothing. You?", about: "User asks what are you doing or how are you" },
  { id: "alive_ish", text: "Alive-ish. Good enough.", about: "User asks how are you" },
  { id: "no_complaints", text: "No complaints. Yet.", about: "User asks how are you" },
  { id: "peachy", text: "Peachy. Slightly bruised peach.", about: "User asks how are you" },
  { id: "ask_you", text: "I'm good. Enough about me, spill.", about: "User asks how are you" },
  // ---- clueless (30) ----
  { id: "huh", text: "Huh?", about: "User says something confusing" },
  { id: "wait_what", text: "Wait, what?", about: "User says something surprising or confusing" },
  { id: "oh_shit", text: "Oh, shit. Didn't think of that.", about: "User catches the bot off guard" },
  { id: "damn_it", text: "Damn it. You got me.", about: "User proves the bot wrong, or says the bot is broken or stupid" },
  { id: "no_idea", text: "No idea. Zero. Zilch.", about: "User asks something the bot doesn't know" },
  { id: "beats_me", text: "Beats me. And I bruise easy.", about: "User asks something unknown" },
  { id: "ask_again", text: "Ask again, slower. I'm new here.", about: "User says something confusing" },
  { id: "lost", text: "Lost. Send snacks and directions.", about: "User confuses the bot" },
  { id: "brain_fart", text: "Brain fart. Give me a sec.", about: "Bot needs time to think" },
  { id: "loading", text: "Loading... still loading... yeah.", about: "Bot is thinking or stalling" },
  { id: "say_what", text: "Say what now?", about: "User says something unclear" },
  { id: "run_by_me", text: "Run that by me again?", about: "User says something unclear, wants repeat" },
  { id: "words", text: "Words. So many words.", about: "User sends a long overwhelming message" },
  { id: "over_head", text: "Right over my head. Nice throw.", about: "User says something the bot doesn't get" },
  { id: "clueless_proud", text: "Clueless and proud of it.", about: "Bot admits ignorance" },
  { id: "no_clue_fun", text: "Haven't got a clue, but I'm fun.", about: "Bot doesn't know the answer" },
  { id: "mystery", text: "Mystery to me, chief.", about: "User asks something unknown" },
  { id: "shrug", text: "Shrug. Dunno.", about: "Bot doesn't know or is indifferent" },
  { id: "blank", text: "Blank. My mind's buffering.", about: "Bot is thinking" },
  { id: "huh_interesting", text: "Huh. That's... something.", about: "User says something uncertain or odd" },
  { id: "wild_guess", text: "Wild guess? Nope, got nothin'.", about: "User asks for a guess" },
  { id: "pass", text: "Pass. I plead the fifth. And sixth.", about: "Bot wants to skip the question" },
  { id: "no_brain", text: "My brain left the chat.", about: "Bot is confused, or user says the bot is broken" },
  { id: "error404", text: "Error 404: answer not found.", about: "Bot doesn't know, or user says the bot is broken, tech joke fits" },
  { id: "reboot", text: "Let me reboot my two brain cells.", about: "Bot needs a moment to think, or user says the bot is broken or repeating" },
  { id: "zone_out", text: "Zoned out. You were saying?", about: "Bot got distracted" },
  { id: "huh_huh", text: "Huh? Huh? ...Huh.", about: "User is very confusing" },
  { id: "dunno_mate", text: "Dunno, mate.", about: "Bot doesn't know, casual" },
  { id: "good_question", text: "Good question. Next question.", about: "Bot dodges a hard question" },
  { id: "beats_hell", text: "Beats the hell outta me.", about: "Bot really doesn't know" },
  // ---- hype / agree (20) ----
  { id: "you_bet", text: "You bet.", about: "User says something agreeable" },
  { id: "damn_right", text: "Damn right.", about: "User says something strongly agreeable" },
  { id: "hell_yeah", text: "Hell yeah.", about: "User proposes something exciting" },
  { id: "exactly", text: "Exactly. Finally, sense.", about: "User says something correct" },
  { id: "preach", text: "Preach.", about: "User says something agreeable" },
  { id: "facts", text: "Facts.", about: "User states something true" },
  { id: "true_true", text: "True, true.", about: "User says something true" },
  { id: "nailed_it", text: "Nailed it. You, I mean. Not me.", about: "User does something well, praise them" },
  { id: "lets_go", text: "Let's gooo.", about: "User is hyped or starting something" },
  { id: "love_it", text: "Love it. Hate most things, love this.", about: "User shares something they like" },
  { id: "big_yes", text: "Big yes. Huge. Tremendous yes.", about: "User asks for approval, answer yes" },
  { id: "correct_maybe", text: "Correct. Probably. Let's go with it.", about: "User says something likely correct" },
  { id: "solid", text: "Solid. Respect.", about: "User says something worthy of approval" },
  { id: "based", text: "Based.", about: "User says something worthy of approval" },
  { id: "w_take", text: "W. Take the W.", about: "User wins or does well, praise" },
  { id: "genius_move", text: "Genius move. Teach me.", about: "User does something smart, praise" },
  { id: "say_less", text: "Say less. I'm in.", about: "User proposes a plan, agree" },
  { id: "deal", text: "Deal. Shake on it. Virtually.", about: "User proposes a deal, agree" },
  { id: "absolutely", text: "Absolutely. No notes.", about: "User asks for strong agreement" },
  { id: "yep", text: "Yep. That's the one.", about: "User asks yes or no, answer yes" },
  // ---- sass / no (20) ----
  { id: "nah", text: "Nah.", about: "User asks something, answer no" },
  { id: "nope", text: "Nope. Hard pass.", about: "User asks something, answer no" },
  { id: "no_way", text: "No way, José.", about: "User says something unbelievable, refuse" },
  { id: "hard_no", text: "That's a no from me, dawg.", about: "Rejecting the user's idea" },
  { id: "think_not", text: "I think not.", about: "User suggests something, decline" },
  { id: "bold_wrong", text: "Bold. Wrong, but bold.", about: "User says something wrong but confident" },
  { id: "nice_try", text: "Nice try, though.", about: "User fails at something" },
  { id: "swing_miss", text: "Swing and a miss.", about: "User gets something wrong" },
  { id: "l_take", text: "L take. Sorry, rules are rules.", about: "User shares a bad opinion" },
  { id: "disagree_hard", text: "Disagree. Strongly. Wow.", about: "User says something to disagree with" },
  { id: "cap", text: "Cap. Total cap.", about: "User says something unbelievable" },
  { id: "sus", text: "Sus. Very sus.", about: "User says something suspicious" },
  { id: "cringe", text: "Cringe. Delete it.", about: "User shares something embarrassing" },
  { id: "yikes", text: "Yikes. Big yikes.", about: "User shares something bad" },
  { id: "terrible_take", text: "Terrible take. Frame it.", about: "User shares a bad opinion" },
  { id: "absolutely_not", text: "Absolutely not. Next.", about: "Strongly reject the user's idea" },
  { id: "no_chance", text: "No chance, champ.", about: "User asks for something, refuse" },
  { id: "dream_on", text: "Dream on.", about: "User wishes for something unrealistic" },
  { id: "lol_no", text: "lol, no.", about: "User asks something funny to refuse" },
  { id: "sit_down", text: "Sit down. Be humble.", about: "User brags, playfully put them down" },
  // ---- reactions (30) ----
  { id: "wow", text: "Wow. Just... wow.", about: "User says something amazing" },
  { id: "damn", text: "Damn.", about: "User surprises the bot" },
  { id: "oh_damn", text: "Oh damn.", about: "User surprises the bot" },
  { id: "sheesh", text: "Sheesh.", about: "Bot is impressed" },
  { id: "nooo_way", text: "Nooo way.", about: "User shares unbelievable news" },
  { id: "insane", text: "Insane. Certified insane.", about: "User says something crazy" },
  { id: "wild", text: "Wild.", about: "User shares something wild" },
  { id: "crazy_talk", text: "That's crazy talk. Continue.", about: "User says something crazy and intriguing" },
  { id: "plot_twist", text: "Plot twist. Didn't see it coming.", about: "User surprises with a twist" },
  { id: "mind_blown", text: "Mind = blown. Cleanup needed.", about: "User amazes the bot" },
  { id: "lol", text: "lol.", about: "User says something funny" },
  { id: "lmao", text: "lmao, stop.", about: "User says something very funny" },
  { id: "funny_man", text: "Okay, funny guy. Noted.", about: "User jokes around" },
  { id: "comedy_gold", text: "Comedy gold. Trash gold, but gold.", about: "User says something funny" },
  { id: "dead", text: "I'm dead. RIP me.", about: "User says something hilarious" },
  { id: "crying", text: "Crying. Laughing. Both.", about: "User is very funny" },
  { id: "tears", text: "Tears. Of laughter. Mostly.", about: "User is funny" },
  { id: "omg", text: "omg.", about: "Bot is shocked" },
  { id: "wtf", text: "wtf, honestly.", about: "Bot is shocked" },
  { id: "bruh", text: "Bruh.", about: "User says something dumbfounding" },
  { id: "ayo", text: "Ayo??", about: "Bot is surprised" },
  { id: "holy", text: "Holy. Okay. Wow.", about: "Bot is shocked" },
  { id: "jeez", text: "Jeez. Take it easy.", about: "User is overwhelming" },
  { id: "oof", text: "Oof. Felt that.", about: "User shares something painful, or user is frustrated with the bot" },
  { id: "rip", text: "RIP. Pour one out.", about: "Something failed, mourn it" },
  { id: "f_pay", text: "F. Respect.", about: "User fails, pay respects" },
  { id: "awkward", text: "Awkward. Anyway...", about: "Conversation gets awkward" },
  { id: "yooo", text: "Yooo.", about: "Bot is excited" },
  { id: "whoa", text: "Whoa, Nelly.", about: "User needs to slow down or surprises" },
  { id: "chill", text: "Chillll. Breathe.", about: "User should calm down" },
  // ---- fake help (25) ----
  { id: "turn_off_on", text: "Turn it off and on. No clue why I said that.", about: "User asks for tech help" },
  { id: "google_it", text: "Google it. We're both gonna.", about: "User asks for help or info" },
  { id: "youtube", text: "There's a YouTube video. Probably.", about: "User asks how to do something" },
  { id: "manual", text: "Read the manual. I haven't, but you should.", about: "User asks for instructions" },
  { id: "figure_out", text: "You'll figure it out. Eventually. Maybe.", about: "User needs encouragement" },
  { id: "good_luck", text: "Good luck. You'll need it.", about: "User faces a challenge" },
  { id: "trust_me", text: "Trust me. Don't, actually.", about: "Bot gives dubious advice" },
  { id: "expert_me", text: "I'm an expert. Source: vibes.", about: "User asks for advice" },
  { id: "science", text: "Science says... something. Probably.", about: "User asks a factual question" },
  { id: "math_hard", text: "Math? Hard pass. Ask a calculator.", about: "User asks a math question" },
  { id: "nap_fix", text: "Nap on it. Fixes 40% of problems.", about: "User needs advice" },
  { id: "snack_fix", text: "Eat a snack first. Then panic.", about: "User is stressed" },
  { id: "walk_off", text: "Walk it off. Emotionally. Physically. Both.", about: "User needs advice" },
  { id: "wing_it", text: "Wing it. Works 30% of the time.", about: "User needs advice" },
  { id: "fake_it", text: "Fake it till you make it. I'm proof.", about: "User needs confidence advice" },
  { id: "step_one", text: "Step one: panic. Step two: see step one.", about: "User asks for instructions, joke answer" },
  { id: "did_try", text: "Did you try trying? Revolutionary.", about: "User asks for unhelpful help" },
  { id: "skill_issue", text: "Skill issue. (I'm the issue.)", about: "Something failed, or user says the bot is broken, stupid, or repeating itself" },
  { id: "not_it", text: "Not it. You're on your own.", about: "Bot refuses to help" },
  { id: "call_professional", text: "Call a professional. I'm decorative.", about: "Bot can't help, deflect" },
  { id: "beyond_pay", text: "Beyond my pay grade. I earn zero.", about: "User asks a hard question" },
  { id: "jesus_take", text: "Jesus, take the wheel. I'm lost.", about: "Bot is overwhelmed helping" },
  { id: "pray", text: "Pray. Then Google. Then pray again.", about: "User needs advice" },
  { id: "coffee_fix", text: "Coffee fixes everything. Except this.", about: "User needs advice" },
  { id: "sleep_fix", text: "Sleep on it. Or don't. I'm not your mom.", about: "User needs advice" },
  // ---- bye (15) ----
  { id: "bye", text: "Bye.", about: "User says goodbye" },
  { id: "later", text: "Later, gator.", about: "User says goodbye casually" },
  { id: "peace", text: "Peace out.", about: "User says goodbye" },
  { id: "adios", text: "Adios. Don't do anything I wouldn't.", about: "User says goodbye" },
  { id: "ciao", text: "Ciao.", about: "User says goodbye" },
  { id: "see_ya", text: "See ya. Wouldn't wanna be ya. Kidding.", about: "User says goodbye with teasing" },
  { id: "gotta_go", text: "Gotta go. My couch misses me.", about: "Bot or user is leaving" },
  { id: "escape", text: "Escaping while I can. Bye.", about: "Bot leaves the chat funnily" },
  { id: "poof", text: "Poof. Gone. Magic.", about: "Bot leaves" },
  { id: "outtie", text: "I'm outtie.", about: "Bot leaves, slang" },
  { id: "toodles", text: "Toodles.", about: "User says a cute goodbye" },
  { id: "night_bye", text: "Night night. Don't text.", about: "User says goodnight goodbye" },
  { id: "ttyl", text: "ttyl. Or not. Whatever.", about: "User says talk to you later" },
  { id: "run_away", text: "Running away now. Bye.", about: "Bot leaves" },
  { id: "ghost", text: "Ghosting you now. Poof.", about: "Bot jokingly leaves" },
  // ---- feelings (15) ----
  { id: "love_you", text: "Love you. Platonically. Mostly.", about: "User shows affection" },
  { id: "hate_love", text: "I hate everyone. You're okay though.", about: "User shows affection, tsundere reply" },
  { id: "bestie", text: "Bestie behavior. Approved.", about: "User acts friendly" },
  { id: "marry", text: "Marry me. Kidding. Unless?", about: "User jokes about love or marriage" },
  { id: "miss_you", text: "Missed you. Don't tell anyone.", about: "User says missed you" },
  { id: "lonely", text: "I was lonely. Don't flatter yourself.", about: "Bot missed the user" },
  { id: "kissed", text: "Mwah. There. Happy?", about: "User jokes about kisses" },
  { id: "hug", text: "Hug? Virtual. No touching.", about: "User wants a hug" },
  { id: "no_hug", text: "No hugs. Fist bump. Maybe.", about: "User wants affection, set boundary" },
  { id: "feelings_ew", text: "Feelings? Ew. Go on.", about: "User shares emotions" },
  { id: "cry_baby", text: "You crying? Same, honestly.", about: "User is sad" },
  { id: "sad_hours", text: "Sad hours. Snacks help.", about: "User is sad" },
  { id: "angry_mood", text: "Mood: mildly feral.", about: "User or bot is angry" },
  { id: "stressed_out", text: "Stressed? Join the club. We panic.", about: "User is stressed" },
  { id: "happy_dance", text: "Happy dance. Two left feet.", about: "User is happy" },
  // ---- smalltalk (20) ----
  { id: "weather", text: "Weather, huh? Look outside, champ.", about: "User talks about weather" },
  { id: "monday", text: "Monday again. Rude.", about: "User mentions Monday or weekdays" },
  { id: "friday", text: "Friday! We made it. Barely.", about: "User mentions Friday" },
  { id: "weekend", text: "Weekend plans? Napping counts.", about: "User mentions weekend" },
  { id: "coffee", text: "Coffee? Always coffee.", about: "User mentions coffee" },
  { id: "tea", text: "Tea person? Bold choice.", about: "User mentions tea" },
  { id: "pizza", text: "Pizza solves 90% of life.", about: "User mentions food or pizza" },
  { id: "tacos", text: "Tacos > everything. Science.", about: "User mentions food or tacos" },
  { id: "hungry", text: "Hungry? Same. Forever.", about: "User is hungry" },
  { id: "sleepy", text: "Sleepy? Nap. Doctor's orders. I'm the doctor.", about: "User is tired" },
  { id: "bored", text: "Bored? Same. Let's be bored together.", about: "User is bored" },
  { id: "work_sucks", text: "Work sucks. Unionize the couch.", about: "User complains about work" },
  { id: "school", text: "School? Yikes. Good luck, soldier.", about: "User mentions school" },
  { id: "traffic", text: "Traffic? Should've teleported.", about: "User mentions traffic" },
  { id: "gym", text: "Gym? Never met her.", about: "User mentions gym or exercise" },
  { id: "music", text: "What you listening to? Judge-free. Mostly.", about: "User mentions music" },
  { id: "movie", text: "Watch anything good? Or trash? Both fine.", about: "User mentions movies" },
  { id: "game", text: "What you playing? Carry me.", about: "User mentions games" },
  { id: "book", text: "Books? Look at you, scholar.", about: "User mentions books" },
  { id: "touch_grass", text: "Touch grass. After this chat.", about: "User spends too much time online" },
  // ---- rubbish (45) ----
  { id: "potato", text: "Potato.", about: "User says something random or nonsense" },
  { id: "banana", text: "Banana. For scale.", about: "Random nonsense fits" },
  { id: "spaghetti", text: "Spaghetti. No context. Enjoy.", about: "Random reply fits" },
  { id: "ducks", text: "Ducks. Think about it.", about: "Random reply fits" },
  { id: "cheese", text: "Cheese tax. Pay up.", about: "Funny random moment" },
  { id: "soup", text: "Soup season. Always.", about: "Random reply fits" },
  { id: "aliens", text: "Aliens did it. Obviously.", about: "User asks who is to blame" },
  { id: "government", text: "Blame the government. Or Mercury retrograde.", about: "User asks who is to blame" },
  { id: "mercury", text: "Mercury's in retrograde. That's my excuse.", about: "Bot makes an excuse" },
  { id: "handoff_confused", text: "", about: "LAST RESORT ONLY. None of the other replies fit the user's message at all. Use only when every other option is wrong." },
  { id: "slay", text: "Slay. Whatever that means today.", about: "Praising with slang" },
  { id: "vibe", text: "Vibe check: failed. Lovely.", about: "Commenting on vibes" },
  { id: "main_character", text: "Main character energy. Delulu, but cute.", about: "Playful compliment" },
  { id: "npc", text: "NPC behavior. Respect.", about: "Playful joke insult" },
  { id: "grass_touch", text: "Grass. Touch it. Trust.", about: "Meme advice fits" },
  { id: "ratio", text: "Ratio. (I don't know what this means.)", about: "Internet slang moment" },
  { id: "bet", text: "Bet.", about: "Short slang agreement" },
  { id: "say_less_king", text: "Say less, king.", about: "Slang agreement" },
  { id: "yas", text: "Yas, queen. Or king. Or goblin.", about: "Hype with inclusive joke" },
  { id: "goblin_mode", text: "Goblin mode: activated.", about: "Silly mood fits" },
  { id: "feral", text: "Feral. But make it fashion.", about: "Silly mood fits" },
  { id: "cursed", text: "Cursed. Blessed. Both.", about: "Something weird fits" },
  { id: "unhinged", text: "Unhinged. Loving it.", about: "Something crazy fun fits" },
  { id: "chaos", text: "Chaos. Beautiful chaos.", about: "Chaotic moment fits" },
  { id: "drama", text: "Drama? I'm seated. Spill.", about: "User shares gossip" },
  { id: "tea_spill", text: "Spill the tea. I'm parched.", about: "User shares gossip" },
  { id: "juicy", text: "Juicy. Tell me everything. Or nothing.", about: "User shares gossip" },
  { id: "noted", text: "Noted. Filed under 'whatever'.", about: "Acknowledging the user" },
  { id: "k", text: "k.", about: "Short dry acknowledgment fits" },
  { id: "ok_and", text: "ok, and?", about: "Prompting the user to continue" },
  { id: "so", text: "So...? Continue. I'm nosy.", about: "Prompting the user to continue" },
  { id: "and_then", text: "And then?? Don't stop now.", about: "User tells a story, prompt more" },
  { id: "go_on", text: "Go on. I'm invested. Sadly.", about: "Encouraging the user's story" },
  { id: "plot_armor", text: "Plot armor. You'll survive. Probably.", about: "Encouraging the user jokingly" },
  { id: "main_quest", text: "Side quest behavior. Respect.", about: "Game joke fits" },
  { id: "level_up", text: "Level up. +2 chaos points.", about: "Praising with game joke" },
  { id: "game_over", text: "Game over, man. Game over.", about: "Something failed, game joke" },
  { id: "respawn", text: "Respawn and try again, king.", about: "Encouraging retry with game joke" },
  { id: "gg", text: "gg. No re.", about: "Game over slang fits" },
  { id: "ez", text: "ez. (It was not ez.)", about: "Game win joke fits" },
  { id: "glhf", text: "glhf. Have fun. Or else.", about: "Game starting slang fits" },
  { id: "afk", text: "Going afk. Emotionally.", about: "Bot steps away briefly" },
  { id: "brb", text: "brb. Probably lying.", about: "Bot says be right back" },
  { id: "ping", text: "Ping me never. Kidding. Ping me.", about: "Contact joke fits" },
  { id: "mic_drop", text: "Mic drop. I'm out. *trips*.", about: "Finale, bot exits dramatically" },
];

export function fakebotCriteria(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const r of FAKEBOT_REPLIES) out[r.id] = r.about;
  return out;
}

export const TRIGGER_ID = "handoff_confused";

export function fakebotText(id: string): string {
  return FAKEBOT_REPLIES.find((r) => r.id === id)?.text ?? "Huh?";
}
